# Generated by Django 4.2.7 on 2023-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Описание задачи')),
                ('date_of_completion', models.DateField(blank=True, null=True, verbose_name='Дата выполнения, вводить в формате YYYY-mm-dd')),
                ('status', models.TextField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=50, verbose_name='Статус задачи')),
            ],
        ),
    ]
